import { getRideDaySettings } from '../storage/ride-day-settings.ts'
import type { RideDaySettingsDocument } from '../storage/ride-day-settings.ts'
import { rga2026TripPlan } from '../trip/plan.ts'
import type { TripPlan } from '../trip/types.ts'
import { renderGpxShareDialog } from './gpx-share.ts'
import { renderImageViewerDialog } from './image-viewer.ts'

function dayEditorDialog(): string {
  return `<dialog class="pause-editor" id="pause-editor" aria-labelledby="pause-editor-title"><form method="dialog" data-pause-editor-form><header><div><p class="eyebrow">Étape sélectionnée</p><h2 id="pause-editor-title">Réglages de l’étape</h2></div><button class="button button--quiet" type="button" data-pause-cancel>Fermer</button></header><fieldset class="day-settings-fields"><legend>Réglages du jour</legend><div class="field field--time"><label for="day-departure-time">Heure de départ</label><div class="field__time-control"><input id="day-departure-time" type="time" data-day-departure-time required></div></div></fieldset><fieldset class="pause-mode"><legend>Mode du plan de pauses</legend><label><input type="radio" name="pause-mode" value="automatic" checked> Automatique</label><label><input type="radio" name="pause-mode" value="custom"> Personnalisé</label></fieldset><div class="field" data-automatic-break-field><label for="day-total-break">Temps total de pause</label><div class="field__control"><input id="day-total-break" type="number" min="0" max="240" step="5" data-day-total-break required><span>minutes</span></div></div><p class="pause-editor__intro" data-pause-intro></p><div class="pause-editor__list" data-pause-editor-list></div><p data-pause-total-summary></p><p role="status" aria-live="polite" data-pause-feedback></p><footer><button class="button button--primary" type="button" data-pause-save>Enregistrer</button><button class="button button--quiet" type="button" data-pause-restore>Restaurer le plan automatique</button><button class="button button--quiet" type="button" data-pause-cancel>Annuler</button></footer></form></dialog>`
}

function renderStageSummary(settings: { readonly departureTime: string; readonly totalBreakMinutes: number }): string {
  return `<dl class="pause-stage__summary" data-pause-stage-summary><div><dt>Départ</dt><dd data-stage-departure>${settings.departureTime}</dd></div><div><dt>Pauses</dt><dd data-stage-breaks>${settings.totalBreakMinutes} min</dd></div><div><dt>Plan</dt><dd data-stage-plan>Automatique</dd></div></dl>`
}

function referenceSpeedSettings(rideDaySettings: RideDaySettingsDocument): string {
  return `<section class="card reference-speed-card" aria-labelledby="reference-speed-title"><header class="view-heading"><p class="eyebrow">Base du calcul des ETA</p><h3 id="reference-speed-title">Vitesse de référence</h3></header><p>Vitesse de référence sur terrain neutre, hors pauses. Le relief du GPX est ensuite appliqué automatiquement.</p><div class="field"><label for="reference-speed">Vitesse de référence</label><div class="field__control"><input id="reference-speed" type="number" min="8" max="40" step="0.5" data-reference-speed value="${rideDaySettings.referenceSpeedKph}" required><span>km/h</span></div></div><button class="button button--primary" type="button" data-save-reference-speed>Enregistrer</button><p role="status" aria-live="polite" data-reference-speed-feedback></p></section>`
}

function settingsView(rideDaySettings: RideDaySettingsDocument): string {
  const rideDays = rga2026TripPlan.days
    .filter((day) => day.type === 'ride')
    .map(
      (day) =>
        `<details class="card pause-stage" data-pause-stage="${day.id}"><summary><strong>${day.id}</strong><span>${day.name}</span></summary>${renderStageSummary(getRideDaySettings(rideDaySettings, day.id))}<button class="button button--quiet" type="button" data-open-pause-editor data-pause-day="${day.id}">Modifier</button></details>`,
    )
    .join('')
  return `<section class="app-view" data-app-view="settings" hidden><button class="button button--quiet" type="button" data-settings-back>← Retour</button><header class="view-heading"><p class="eyebrow">Préférences locales</p><h2>Réglages</h2><p>La vitesse de référence est commune aux dix journées roulées. Heure de départ et pauses restent réglables par étape.</p></header>${referenceSpeedSettings(rideDaySettings)}<section class="pause-stages" aria-labelledby="pause-stages-title"><header class="view-heading"><h3 id="pause-stages-title">Réglages par étape</h3></header>${rideDays}</section>${dayEditorDialog()}<details class="card technical-details settings-diagnostics" data-sources-sheet><summary>Diagnostic et sources</summary><h3>Diagnostic roadbook / GPX</h3><div data-roadbook-diagnostics data-roadbook-diagnostic-state="loading" aria-busy="true"></div><h3>Analyse des traces GPX</h3><div data-gpx-analysis data-gpx-state="loading" aria-busy="true"></div></details></section>`
}

/**
 * Bug 48B closeout: `<h1>RGA 2026</h1><p>Route des Grandes Alpes</p>` and
 * `data-day-indicator`'s initial `"J1 sur ${plan.totalDays}"` are the RGA
 * golden-master's own static content — kept as-is here, since this function
 * (and its `plan` default) is still exactly what the legacy RGA runtime and
 * its golden-master tests exercise. For a real user, `main.ts` overwrites
 * `.brand`/`[data-day-indicator]` synchronously at boot, before the
 * IndexedDB database even opens (`applyGenericAppHeader`), so this markup is
 * only ever visible to the legacy/test paths, never to the generic app.
 */
export function renderDashboard(rideDaySettings: RideDaySettingsDocument, plan: TripPlan = rga2026TripPlan): string {
  return `<div class="app-shell"><header class="app-header"><div class="app-header__inner"><div class="brand"><h1>RGA 2026</h1><p>Route des Grandes Alpes</p></div><span class="stage-indicator" data-day-indicator>J1 sur ${plan.totalDays}</span></div></header><p class="network-status" data-network-status role="status" aria-live="polite" hidden>Mode hors ligne · données locales disponibles</p><main class="dashboard">
  <section class="app-view" data-app-view="today"><header class="view-heading"><p class="eyebrow">Vue d’ensemble du voyage</p><h2>Aperçu</h2></header><div class="overview" data-today-panel data-today-state="loading"><p role="status">Préparation de l’aperçu…</p></div><dialog class="route-map-dialog" data-overview-map-dialog aria-labelledby="overview-expanded-map-title"><header><h2 id="overview-expanded-map-title">Carte du voyage</h2><div class="route-map-dialog__actions"><button class="button button--quiet" type="button" data-overview-close-map>Fermer</button></div></header><div class="route-map-dialog__map-wrap"><div class="route-map route-map--expanded" data-overview-map-expanded></div><p class="route-map__fallback route-map__fallback--expanded" data-overview-map-expanded-fallback hidden>Fond de carte indisponible. Le tracé et les marqueurs locaux restent accessibles.</p></div></dialog></section>
  <section class="app-view" data-app-view="trip" hidden><header class="view-heading"><p class="eyebrow">12 jours · 10 roulés · 2 OFF</p><h2>Voyage</h2></header><div class="trip-plan" data-trip-plan data-trip-state="loading" aria-busy="true"><p role="status">Préparation du voyage…</p></div></section>
  <section class="app-view" data-app-view="day-detail" hidden><div class="detail-nav"><button class="button button--quiet" type="button" data-detail-back>← Retour</button><div><button class="button button--quiet" type="button" data-day-previous aria-label="Journée précédente">‹</button><button class="button button--quiet" type="button" data-day-next aria-label="Journée suivante">›</button></div></div><header class="card day-header" data-day-header><p role="status">Préparation de la journée…</p></header>
    <section class="card route-map-card" data-route-visuals><div class="section-heading"><div><p class="eyebrow">Trace GPX</p><h3>Carte de l’étape</h3></div><button class="button button--quiet" type="button" data-explore-map>Explorer la carte</button></div><div class="route-map" data-route-map></div></section>
    <dialog class="route-map-dialog" data-route-map-dialog aria-labelledby="expanded-map-title"><header><h2 id="expanded-map-title">Carte de l’étape</h2><div class="route-map-dialog__actions"><button class="button button--quiet" type="button" data-practical-layers-toggle aria-expanded="false" aria-controls="practical-layers-panel" hidden>Calques</button><button class="button button--quiet" type="button" data-close-map>Fermer</button></div></header><div class="route-map-dialog__map-wrap"><div class="route-map route-map--expanded" data-route-map-expanded></div><p class="route-map__fallback route-map__fallback--expanded" data-expanded-route-map-fallback hidden>Fond de carte indisponible. Le tracé et les marqueurs locaux restent accessibles.</p><button class="practical-layers-backdrop" type="button" data-practical-layers-backdrop aria-label="Fermer les calques pratiques" tabindex="-1" hidden></button><section class="practical-layers-panel" id="practical-layers-panel" data-practical-layers-panel role="dialog" aria-labelledby="practical-layers-title" hidden><header><div><p class="eyebrow">À 6 km maximum du GPX</p><h3 id="practical-layers-title">Calques pratiques</h3></div><button class="button button--quiet" type="button" data-practical-layers-close>Fermer</button></header><div class="practical-layers-list" data-practical-layers-list></div><footer><button class="button button--quiet button--full" type="button" data-practical-layers-hide-all>Tout masquer</button></footer></section></div></dialog>
    <section class="card elevation-profile-card" data-route-visuals><p class="eyebrow">Relief</p><h3>Profil altimétrique</h3><div data-elevation-profile></div></section>
    <nav class="day-tabs" role="tablist" aria-label="Sections de la journée"><button id="day-tab-route" type="button" role="tab" data-day-tab="route" aria-controls="day-panel-route" aria-selected="true" tabindex="0">Parcours</button><button id="day-tab-weather" type="button" role="tab" data-day-tab="weather" aria-controls="day-panel-weather" aria-selected="false" tabindex="-1">Météo</button><button id="day-tab-infos" type="button" role="tab" data-day-tab="infos" aria-controls="day-panel-infos" aria-selected="false" tabindex="-1">Infos</button></nav>
    <section id="day-panel-route" class="card" role="tabpanel" aria-labelledby="day-tab-route" data-day-panel="route"><div class="section-heading"><div><p class="eyebrow">Lieux documentés, ordre et horaires</p><h3>Parcours</h3></div></div><div data-route-engine data-route-state="loading" aria-busy="true"><p role="status">Analyse de la trace GPX…</p></div></section>
    <section id="day-panel-weather" class="card weather-card" role="tabpanel" aria-labelledby="day-tab-weather" data-day-panel="weather" hidden><div class="section-heading weather-card__heading"><div><p class="eyebrow">Conditions qui influencent la décision</p><h3>Météo</h3></div><button class="button button--quiet" type="button" data-weather-refresh>Actualiser</button></div><div class="weather-status-line"><span class="tag tag--data" data-weather-status role="status">En attente</span><time data-weather-updated-at>Aucune actualisation</time></div><div id="selected-day-weather" data-weather-panel data-weather-state="loading" data-weather-source="none" data-weather-refreshing="false" data-weather-has-data="false" aria-busy="true"><p role="status">Chargement de la météo…</p></div></section>
    <section id="day-panel-infos" class="card day-infos" role="tabpanel" aria-labelledby="day-tab-infos" data-day-panel="infos" hidden><p class="eyebrow">Éditorial et logistique</p><h3>Infos</h3><div data-day-infos-content><p role="status">Chargement des informations…</p></div><div data-accommodation-card hidden></div><button class="button button--primary button--full" type="button" data-gpx-download hidden>GPX</button></section>
  </section>
  <section class="app-view" data-app-view="trips" hidden><div data-trips-manager><p role="status">Chargement de vos voyages…</p></div></section>
  ${settingsView(rideDaySettings)}${renderGpxShareDialog()}${renderImageViewerDialog()}</main><nav class="app-nav" aria-label="Navigation principale"><a href="#/today" data-nav-view="today">Aperçu</a><a href="#/trip" data-nav-view="trip">Voyage</a><a href="#/trips" data-nav-view="trips">Mes voyages</a></nav><div class="visually-hidden" id="save-status" role="status" aria-live="polite"></div></div>`
}
