import type { DashboardSettings } from '../storage/settings.ts'
import { rga2026TripPlan } from '../trip/plan.ts'
import type { TripPlan } from '../trip/types.ts'

function settingsView(settings: DashboardSettings): string {
  return `<section class="app-view" data-app-view="settings" hidden><button class="button button--quiet" type="button" data-settings-back>← Retour</button><header class="view-heading"><p class="eyebrow">Préférences locales</p><h2>Réglages</h2><p>Réglages globaux pour les dix journées roulées. Ils recalculent les ETA et la météo associée.</p></header><form class="card settings-form" id="settings-form"><div class="field"><label for="average-speed">Vitesse moyenne</label><div class="field__control"><input id="average-speed" type="number" min="8" max="40" step="0.5" value="${settings.averageSpeedKph}" required><span>km/h</span></div></div><div class="field"><label for="departure-time">Heure de départ</label><input id="departure-time" type="time" value="${settings.departureTime}" required></div><div class="field"><label for="break-duration">Durée totale des pauses</label><div class="field__control"><input id="break-duration" type="number" min="0" max="240" step="5" value="${settings.totalBreakMinutes}" required><span>minutes</span></div></div><p id="settings-feedback" role="status" aria-live="polite"></p><div class="settings-actions"><button class="button button--primary" type="submit">Enregistrer</button><button class="button button--quiet" type="button" data-restore-settings>Valeurs par défaut</button></div></form></section>`
}

export function renderDashboard(settings: DashboardSettings, plan: TripPlan = rga2026TripPlan): string {
  return `<div class="app-shell"><header class="app-header"><div class="app-header__inner"><div class="brand"><h1>RGA 2026</h1><p>Route des Grandes Alpes</p></div><span class="stage-indicator" data-day-indicator>J1 sur ${plan.totalDays}</span></div></header><main class="dashboard">
  <section class="app-view" data-app-view="today"><header class="view-heading"><p class="eyebrow">L’essentiel maintenant</p><h2>Aujourd’hui</h2></header><article class="card today-card" data-today-panel data-today-state="loading"><p role="status">Préparation de la journée…</p></article></section>
  <section class="app-view" data-app-view="trip" hidden><header class="view-heading"><p class="eyebrow">12 jours · 10 roulés · 2 OFF</p><h2>Voyage</h2></header><div class="trip-plan" data-trip-plan data-trip-state="loading" aria-busy="true"><p role="status">Préparation du voyage…</p></div></section>
  <section class="app-view" data-app-view="day-detail" hidden><div class="detail-nav"><button class="button button--quiet" type="button" data-detail-back>← Retour</button><div><button class="button button--quiet" type="button" data-day-previous aria-label="Journée précédente">‹</button><button class="button button--quiet" type="button" data-day-next aria-label="Journée suivante">›</button></div></div><header class="view-heading"><p class="eyebrow">Journée sélectionnée</p><h2>Détail</h2><div class="detail-links"><a href="#/settings">Réglages</a><button type="button" data-open-roadbook>Roadbook</button><button type="button" data-open-sources>Sources et données</button></div></header>
    <nav class="day-tabs" aria-label="Sections de la journée"><button type="button" data-day-tab="timeline" aria-selected="true">Chronologie</button><button type="button" data-day-tab="points" aria-selected="false">Points</button><button type="button" data-day-tab="weather" aria-selected="false">Météo</button></nav>
    <section class="card" data-day-panel="timeline"><h3>Parcours et chronologie</h3><div data-route-engine data-route-state="loading" aria-busy="true"><p role="status">Analyse de la trace GPX…</p></div></section>
    <section class="card" data-day-panel="points" hidden><h3>Points de passage</h3><div data-day-points><p role="status">Préparation des points…</p></div></section>
    <section class="card weather-card" data-day-panel="weather" hidden><div class="section-heading weather-card__heading"><div><p class="eyebrow">Décision opérationnelle</p><h3>Météo et risques</h3></div><button class="button button--quiet" type="button" data-weather-refresh>Actualiser</button></div><div class="weather-status-line"><span class="tag tag--data" data-weather-status role="status">En attente</span><time data-weather-updated-at>Aucune actualisation</time></div><div id="selected-day-weather" data-weather-panel data-weather-state="loading" data-weather-source="none" data-weather-refreshing="false" data-weather-has-data="false" aria-busy="true"><p role="status">Chargement de la météo…</p></div></section>
    <details class="card secondary-sheet" data-roadbook-sheet><summary>Roadbook</summary><div data-roadbook-detail data-roadbook-detail-state="loading" aria-busy="true"><p role="status">Chargement du roadbook…</p></div></details>
    <details class="card technical-details" data-sources-sheet><summary>Sources et données</summary><h3>Diagnostic roadbook / GPX</h3><div data-roadbook-diagnostics data-roadbook-diagnostic-state="loading" aria-busy="true"></div><h3>Analyse des traces GPX</h3><div data-gpx-analysis data-gpx-state="loading" aria-busy="true"></div></details>
  </section>${settingsView(settings)}</main><nav class="app-nav" aria-label="Navigation principale"><a href="#/today" data-nav-view="today">Aujourd’hui</a><a href="#/trip" data-nav-view="trip">Voyage</a><a href="#/settings" data-nav-view="settings">Réglages</a></nav><div class="visually-hidden" id="save-status" role="status" aria-live="polite"></div></div>`
}
